server:
  port: 8080

spring:
  application:
    name: ui-service
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      service: ${spring.application.name}

saga:
  order-service-url: http://localhost:8081
  inventory-service-url: http://localhost:8083

logging:
  level:
    com.quanla.sagademo: DEBUG
